# Generated by Django 5.2.6 on 2025-09-23 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='newsletter_subscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
