# Generated by Django 5.2.6 on 2025-09-22 22:53

import bank_statement.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=bank_statement.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'tiff'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.PositiveIntegerField()),
                ('bank_name', models.CharField(choices=[('snb', 'Saudi National Bank'), ('alrajhi', 'Al Rajhi Bank'), ('riyad', 'Riyad Bank'), ('sab', 'Saudi Awwal Bank'), ('bsf', 'Banque Saudi Fransi'), ('anb', 'Arab National Bank'), ('alinma', 'Alinma Bank'), ('albilad', 'Bank AlBilad'), ('aljazira', 'Bank AlJazira'), ('saib', 'Saudi Investment Bank'), ('other', 'Other')], default='other', max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('statement_period_start', models.DateField(blank=True, null=True)),
                ('statement_period_end', models.DateField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('encryption_key', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='bank_statement.statement')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('category', models.CharField(choices=[('atm_withdrawal', 'ATM Withdrawal'), ('pos_purchase', 'POS Purchase'), ('online_transfer', 'Online Transfer'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('salary', 'Salary'), ('interest', 'Interest'), ('charges', 'Bank Charges'), ('refund', 'Refund'), ('other', 'Other')], default='other', max_length=20)),
                ('raw_description', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_statement.statement')),
            ],
            options={
                'ordering': ['-transaction_date', '-extracted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['user', 'upload_date'], name='bank_statem_user_id_6aca26_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['processing_status'], name='bank_statem_process_86492d_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['bank_name'], name='bank_statem_bank_na_251087_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['statement', 'transaction_date'], name='bank_statem_stateme_e4cb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='bank_statem_transac_e86a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='bank_statem_categor_3a7db2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['needs_review'], name='bank_statem_needs_r_07fc41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('statement', 'transaction_date', 'description', 'debit_amount', 'credit_amount')},
        ),
    ]
